apiVersion: v1
kind: Service
metadata:
  name: wsrestorden
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:887482798966:certificate/541a4741-02a6-450b-8514-a6fd11bff86b
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  namespace: dev
spec:
  ports:
    - port: 18080
      name: http
      targetPort: 18080
      protocol: TCP
    - port: 443      
      name: https
      targetPort: 18080
      protocol: TCP
  type: LoadBalancer    
  selector:
    app: wsrestorden