spring:
  application:
    name: wsRestOrden
server:
  port: 18080
eureka:
  client:
    serviceUrl:
      defaultZone: ${POC_EUREKA_URI}
  instance:
    preferIpAddress: true
    status-page-url-path: /api/orden/add
    health-check-url-path: /api/orden/health
    virtual-host-name: SBBOGLAPPROJB14
    metadata-map:
      app-owner: Sophos Solutions
      description: Servicio para registrar una Orden